### ISSUE TITLE
Non-currency assets are displayed as "XXX"

### ISSUE THREAD

**Issue by Kaligula0** [GnuCash-Pocket/gnucash-android#34]
## Steps to reproduce the behaviour
1. Import a book or account tree with account(s) that use(s) non-currency asset(s) (stock or another custom asset, e.g. GOOGL stock)
2. Enter a transaction in GnuCash-Pocket app using the account with such stock

## Expected behaviour
App should display this stock as "currency"

## Actual behaviour
App displays "XXX"
![image](https://github.com/GnuCash-Pocket/gnucash-android/assets/3950811/709ee1e5-52da-4abe-a1c4-307e84115626)

## Software specifications
* GnuCash Android version: 2.4.0-dev3_r4caab7a
* System Android version: 14
* Device type: SM-S901B

**Comment by armanschwarz** [comment]
This limitation also means that in the parent account the asset value is ignored, meaning all dollar amounts are incorrect for accounts that have child non-currency accounts.

**Comment by djbrown** [comment]
@Kaligula0 @armanschwarz ist this issue solved in the newest version?

see also #178

**Comment by Kaligula0** [comment]
By "the newest" you mean the version form Play Store? – No, I even can't import account tree to the app (CSV file exported from GnuCash).

**Comment by Kaligula0** [comment]
Same with latest build here (from 19 Dec https://github.com/GnuCash-Pocket/gnucash-android/actions/runs/12415545867)

**Comment by armanschwarz** [comment]
@djbrown apologies for taking so long to respond. I'm still seeing this issue, in that assets are not showing any value in the local currency despite having a net asset value.

![Image](https://github.com/user-attachments/assets/3fdd31b3-93da-4582-b726-934a5e031233)

**Comment by pnemonic78** [comment]
Account balances depend on prices.
If the stock has no corresponding price, then its balance will be 0.00
